### ISSUE TITLE
Duplicate content in Seminar Modul 

### ISSUE THREAD

**Issue by enilee** [oliverklee/ext-seminars#33] opened 2018-04-12 14:53 UTC
Hello,

TYPO3 8.7.10
Seminars 1.4.1 (pre/8-compatibility)

i mean, thats a bug ;)

![image](https://user-images.githubusercontent.com/17785409/38685211-a1ec276a-3e71-11e8-8bb9-c5ec0222ffc6.png)

The Eventlist too

**Comment by oliverklee** [comment] 2018-04-12 15:17
Hi @enilee Please (always) post which seminars version/branch you're using and which TYPO3 version. Thanks!

**Comment by enilee** [comment] 2018-04-17 07:05
I have updated my first post ...

**Comment by oliverklee** [comment] 2018-04-17 07:44
@enilee Are you sure that you're using the version tagged as 1.4.1 (from the TER or from Packagist) and not the `pre/8-compatibility` branch? (1.4.1 and the current master are not able to display the BE module in TYPO3 8.7 yet.)

**Comment by enilee** [comment] 2018-04-17 08:05
I did not know exactly if I should write it publicly. I have updated the post and I know for the future.

**Comment by oliverklee** [comment] 2018-04-25 17:28
Closing. @enilee, please feel to reopen this ticket if the problem still persists.

**Closed by oliverklee** 2018-04-25 17:28 UTC
Labels: bug, waiting for feedback

**Comment by enilee** [comment] 2018-04-26 10:17
Hi,

I updated the Extension successfully to d293e45.

It is still displayed twice.

#### 01 duplicate Event list 
Modul seminars > seminar storage folder > and then this list view displayed duplicated
if you then press on the rider "events", the list is displayed correctly.

#### 02 Duplicate Email view for registered users
Modul seminars > seminar storage folder > in the list view click on the button "email"
then you get a double view liek picture at top of these issue

![image](https://user-images.githubusercontent.com/17785409/39300342-a61da6bc-494b-11e8-84b6-efd5f3ebdc22.png)

**Comment by oliverklee** [comment] 2018-04-26 11:03
> Modul seminars > seminar storage folder > and then this list view displayed duplicated

What the URL of the content frame?

**Comment by oliverklee** [comment] 2018-04-26 11:03
> Modul seminars > seminar storage folder > in the list view click on the button "email"
then you get a double view liek picture at top of these issue

Does this also happen if you click on the "Events" tab first?

**Comment by enilee** [comment] 2018-04-26 11:26
>Does this also happen if you click on the "Events" tab first?

no. 

 >What's the URL of the content frame?

Do you mean a url like this:
typo3/index.php?route=%2Fseminars%2Fconfiguration%2F&token=

**Comment by oliverklee** [comment] 2018-04-26 13:15
No, I mean something like this:

http://typo376.test/typo3/index.php?M=tools_txphpunitbeM1&moduleToken=3055850e9364d54da765c…

I right-click in the frame, select "view frame source", and then use that URL (with the `view-source:` removed).

**Comment by enilee** [comment] 2018-04-26 14:16
I think thats it..

/typo3/index.php?route=%2Fseminars%2Fconfiguration%2F&token=XY&id=68

![image](https://user-images.githubusercontent.com/17785409/39311152-6ed440f0-496c-11e8-8070-86afab7d7d9a.png)

console errors: 
![image](https://user-images.githubusercontent.com/17785409/39311356-00f25724-496d-11e8-9d74-3ccdf90813cc.png)

---
clear console..
after clicking on the tab Events the frame URL:

![image](https://user-images.githubusercontent.com/17785409/39311260-c068e2fe-496c-11e8-8ec6-20ce4bacb93a.png)

no errors in console

**Comment by oliverklee** [comment] 2018-05-09 14:52
Hi @enilee, I still cannot reproduce this problem on my machine. However, I've just removed all `echo` statements from the BE module code. Could you please retest with the current master whether this resolves this problem for you, and then report back here? Thanks!
