### ISSUE TITLE
PHP 8.1 Undefined array key "showRange"

### ISSUE THREAD

**Issue by wmarie-joseph** [oliverklee/ext-seminars#2421] opened 2023-03-03 16:28 UTC
TYPO3 Version : 11.5.22
PHP Version : 8.1
Seminars version : 5.1.0

Hello,

After creating a large amount of events/seminars, in the frontend where the list view is showed, i have an undefined array key, here is the error below : 

![Capture d’écran 2023-03-03 à 17 27 28](https://user-images.githubusercontent.com/110893514/222774089-8198052e-dca1-497a-9f17-ce29c83b11b4.png)

Thank you and best regards,

W

**Comment by oliverklee** [comment] 2023-03-03 17:18
Hi, thanks for reporting this, @wmarie-joseph!

This is a bug in the TYPO3 Core, not in the seminars extension. I'll create a fix for this during the next few days.

**Comment by oliverklee** [comment] 2023-03-04 09:48
Reopening. I think we could work around this in the seminars code, too.

**Comment by oliverklee** [comment] 2023-03-04 09:58
@wmarie-joseph Could you please test whether the fix in #2422 solves this problem for you?

**Comment by oliverklee** [comment] 2023-03-04 10:56
This is the Core fix: https://review.typo3.org/c/Packages/TYPO3.CMS/+/78022

**Comment by wmarie-joseph** [comment] 2023-03-06 08:38
> @wmarie-joseph Could you please test whether the fix in #2422 solves this problem for you?

Hello @oliverklee, 

Thanks for your quick reply !

Unfortunately this patch does not solve the issue, i still have the same error.

**Comment by oliverklee** [comment] 2023-03-06 09:03
@wmarie-joseph Thanks for testing. Then we indeed need the core fix.

You can help by having a look at [the core fix](https://review.typo3.org/c/Packages/TYPO3.CMS/+/78022) and vote "Code review +1" if it looks good to you, and "Verified +1" if it solves the problem for you.

**Comment by wmarie-joseph** [comment] 2023-03-06 09:25
> @wmarie-joseph Thanks for testing. Then we indeed need the core fix.
> 
> You can help by having a look at [the core fix](https://review.typo3.org/c/Packages/TYPO3.CMS/+/78022) and vote "Code review +1" if it looks good to you, and "Verified +1" if it solves the problem for you.

@oliverklee ,

After only installing [this core fix](https://review.typo3.org/c/Packages/TYPO3.CMS/+/78022), i have the following error in the FE :

![Capture d’écran 2023-03-06 à 10 21 08](https://user-images.githubusercontent.com/110893514/223069315-7ac36d7d-b76d-4ced-a743-3d651a8c701c.png)

The BE is accessible, but i can't flush caches

Best regards,

W

**Comment by wmarie-joseph** [comment] 2023-03-07 09:38
> This is strange: This crash doesn't seem related to my core change.

I don't understand either, but i only got this error after updating the AbstractPlugin.php.

What can i do ?

**Comment by oliverklee** [comment] 2023-03-07 10:24
A stacktrace for the first crash would also be helpful.

**Comment by oliverklee** [comment] 2023-03-07 12:32
Also, a way for me to reproduce the problem would be really helpful.

**Comment by oliverklee** [comment] 2023-03-08 17:18
My fix now has been merged into the 11LTS branch of the core. Could you please test whether the problem is gone if you use that branch?

**Comment by wmarie-joseph** [comment] 2023-03-10 10:05
> My fix now has been merged into the 11LTS branch of the core. Could you please test whether the problem is gone if you use that branch?

Hi @oliverklee ,

I tried installing the core from this branch https://github.com/TYPO3/typo3/tree/11.5,  i had some issues because the index.php was missing so i added the index.php from the last version i had. Now i have this error in the apache logs :

<img width="1392" alt="Capture d’écran 2023-03-10 à 10 58 19" src="https://user-images.githubusercontent.com/110893514/224287343-5edeee54-d041-48b0-bc57-bd2421e1462d.png">

How can i properly install the core from that branch (legacy installation)

Thanks and best regards,

W

**Comment by oliverklee** [comment] 2023-03-10 10:24
You probably have a directory with the TYPO3 source to which you symlink. You can try checking out TYPO3 source and then use that as the symlink target.

**Comment by wmarie-joseph** [comment] 2023-03-13 14:23
Hello @oliverklee ,

This issue has been fixed with the typo3 version 11.5.25-dev ! 

Thanks and best regards,

W

**Comment by oliverklee** [comment] 2023-03-13 15:00
Thanks for the head-up. That's great to hear! Closing.

**Closed by oliverklee** 2023-03-13 15:00 UTC
Labels: bug, waiting for feedback
